services:
  postgres:
    image: postgres:16
    container_name: music-streaming-postgres

    environment:
      POSTGRES_DB: music_streaming
      POSTGRES_USER: music_streaming_user
      POSTGRES_PASSWORD: music_streaming_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: